### ISSUE TITLE
Parser Exception for empty set

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/bmoth#40]
For the following machine 
```
MACHINE SimpleSetIncrease
VARIABLES myset, xx
INVARIANT myset <: 1..1000 & xx< 10000 
INITIALISATION myset := {} || xx:= 1
OPERATIONS
  incset = BEGIN myset := myset \/ { xx } || xx:= xx*2 END
END
```
I get:
```
Exception in thread "JavaFX Application Thread" de.bmoth.exceptions.ParseErrorException: no viable alternative at input '{}'
        at de.bmoth.parser.ErrorListener.syntaxError(ErrorListener.java:16)
        at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
        at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:564)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:308)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:145)
        at de.bmoth.antlr.BMoThParser.expression(BMoThParser.java:2079)
```

**Comment by dohan** [comment]
fixed by d3d4ba312793624edfdbd5f4df666d1213420bb2
