### ISSUE TITLE
Pretty-printer for nested declarations

### ISSUE THREAD

**Issue by Jessypet** [hhu-stups/bmoth#82]
So far REPL gives 
```
x = {(1,2)}
{x={(couple 1 2)}}
```
because the pretty-printer is not yet checking for nested datatypes.

**Comment by Jessypet** [comment]
Recursion is now done and can be extended. But sets within tuples are still not working as in that case the sets are represented as 
```
(_ as-array k!2)
```
and apparently can't be converted to the FuncInterp that normally gives information about the sets...

**Comment by Jessypet** [comment]
Also there are two cases that give Exceptions: 
 ```
x = {1,2,(3,4)}
Exception in thread "JavaFX Application Thread" Expected INTEGER but found INTEGER  at '(3,4)' starting in line 1 column 9.
	at de.bmoth.parser.ast.TypeChecker.unify(TypeChecker.java:457)
	at de.bmoth.parser.ast.TypeChecker.visitExprOperatorNode(TypeChecker.java:275)
	at de.bmoth.parser.ast.TypeChecker.visitExprOperatorNode(TypeChecker.java:11)
	at de.bmoth.parser.ast.AbstractVisitor.visitExprNode(AbstractVisitor.java:13)
	at de.bmoth.parser.ast.TypeChecker.visitExprOperatorNode(TypeChecker.java:246)
	at de.bmoth.parser.ast.TypeChecker.visitExprOperatorNode(TypeChecker.java:11)
	at de.bmoth.parser.ast.AbstractVisitor.visitExprNode(AbstractVisitor.java:13)
	at de.bmoth.parser.ast.TypeChecker.visitPredicateOperatorWithExprArgs(TypeChecker.java:155)
	at de.bmoth.parser.ast.TypeChecker.visitPredicateOperatorWithExprArgs(TypeChecker.java:11)
	at de.bmoth.parser.ast.AbstractVisitor.visitPredicateNode(AbstractVisitor.java:44)
	at de.bmoth.parser.ast.TypeChecker.<init>(TypeChecker.java:86)
	at de.bmoth.parser.ast.TypeChecker.typecheckFormulaNode(TypeChecker.java:22)
	at de.bmoth.parser.Parser.getFormulaAsSemanticAst(Parser.java:83)
	at de.bmoth.app.ReplController.processPredicate(ReplController.java:44)
	at de.bmoth.app.ReplController.lambda$initialize$0(ReplController.java:33)
```
and 
```
x = {1,2,{3,4}}
Exception in thread "JavaFX Application Thread" Expected INTEGER but found INTEGER  at '{3,4}' starting in line 1 column 9.
	at de.bmoth.parser.ast.TypeChecker.unify(TypeChecker.java:457)
	at de.bmoth.parser.ast.TypeChecker.visitExprOperatorNode(TypeChecker.java:243)
	at de.bmoth.parser.ast.TypeChecker.visitExprOperatorNode(TypeChecker.java:11)
	at de.bmoth.parser.ast.AbstractVisitor.visitExprNode(AbstractVisitor.java:13)
	at de.bmoth.parser.ast.TypeChecker.visitExprOperatorNode(TypeChecker.java:246)
	at de.bmoth.parser.ast.TypeChecker.visitExprOperatorNode(TypeChecker.java:11)
	at de.bmoth.parser.ast.AbstractVisitor.visitExprNode(AbstractVisitor.java:13)
	at de.bmoth.parser.ast.TypeChecker.visitPredicateOperatorWithExprArgs(TypeChecker.java:155)
	at de.bmoth.parser.ast.TypeChecker.visitPredicateOperatorWithExprArgs(TypeChecker.java:11)
	at de.bmoth.parser.ast.AbstractVisitor.visitPredicateNode(AbstractVisitor.java:44)
	at de.bmoth.parser.ast.TypeChecker.<init>(TypeChecker.java:86)
	at de.bmoth.parser.ast.TypeChecker.typecheckFormulaNode(TypeChecker.java:22)
	at de.bmoth.parser.Parser.getFormulaAsSemanticAst(Parser.java:83)
	at de.bmoth.app.ReplController.processPredicate(ReplController.java:44)
	at de.bmoth.app.ReplController.lambda$initialize$0(ReplController.java:33)
```

**Comment by wysiib** [comment]
Both are not correctly typed anyway. B does not permit sets with elements of different types! So I do not see an issue here.

**Comment by wysiib** [comment]
For the first one, I think you might be able to find the definition of k!2 somewhere in the model. I guess this is merely a reference to it, not the value itself.

**Comment by Jessypet** [comment]
> Both are not correctly typed anyway. B does not permit sets with elements of different types! So I do not see an issue here.

I assumed that but wasn't sure.

> For the first one, I think you might be able to find the definition of k!2 somewhere in the model. I guess this is merely a reference to it, not the value itself.

It's actually not only a set-within-tuple-problem but a set-within-anything-else-problem. 

I tried a lot of combinations but so far I didn't find anything. I will explain the problem more detailed: 

To access the entries of a set a _FuncInterp_ returned by getFuncInterp is needed. But for all other datatypes we need a _Expr_ returned by getConstInterp. 

Let's say we have a couple. We get the _Expr_ and find out that one of the elements (which are _Expr_ s as well returned by Expr.getArgs()) is a set. Now we have an _Expr_ that we know is a set, but with this _Expr_-representation we cannot get any information about it's elements as Expr.getArgs() for a set is empty. We can then actually get a _FuncInterp_ for it by doing model.getFuncInterp(_Expr_.getFuncDecl()), but that is always just null.

Starting with a set we go a different path, but end up at the same barrier. We start with the _FuncInterp_. We can access the entries of that set by calling _FuncInterp_.getEntries(). Each _Entry_ follows the pattern [variable, true] which leads to an _Entry_ [x, true] for each x in the set. So if x is a set as well, we get an _Entry_ 

```
[(_ as-array k!6), true].
```
Now to get the first element of this _Entry_ we have to call getArgs() on it and - of course - that returns an _Expr_. And there we have the same problem as before.

Maybe I just don't see the way to do it, but I'm a bit out of ideas...
